import type { JobApplication } from './types';

export const seedApplications: Omit<JobApplication, 'id' | 'userId' | 'lastUpdated'>[] = [
    {
        company: 'Mountain Warehouse',
        role: 'Casual Retail Sales Assistant',
        location: 'Taupo Store',
        dateApplied: '2025-11-17',
        status: 'Applied',
        url: 'https://example.com/jobs/mountain-warehouse-retail',
    },
    {
        company: 'Hamilton City Council',
        role: 'Senior Service Desk Analyst',
        location: 'Council Office',
        dateApplied: '2025-11-17',
        status: 'Applied',
        url: 'https://example.com/jobs/hamilton-service-desk',
    },
    {
        company: 'JD Sports Australia & NZ',
        role: 'Footwear Sales Assistant',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-11-17',
        status: 'Applied',
        url: 'https://example.com/jobs/jd-sports-footwear',
    },
    {
        company: 'The Just Group (Jay Jays)',
        role: 'Christmas Casual',
        location: 'The Base, Waikato',
        dateApplied: '2025-11-16',
        status: 'Applied',
        url: 'https://example.com/jobs/jay-jays-casual',
    },
    {
        company: 'Bhogal Limited',
        role: 'Courier Driver',
        location: 'Te Rapa, Waikato',
        dateApplied: '2025-11-16',
        status: 'Applied',
        url: 'https://example.com/jobs/bhogal-driver',
    },
    {
        company: 'Datacom',
        role: 'Application Support Analyst',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-11-14',
        status: 'Interviewing',
        url: 'https://example.com/jobs/datacom-support',
    },
    {
        company: 'Red Path N Tables',
        role: 'Christmas Helpers',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-11-14',
        status: 'Applied',
        url: 'https://example.com/jobs/red-path-helpers',
    },
    {
        company: 'DEAR Motors',
        role: 'General Fitter',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-10-30',
        status: 'Viewed',
        url: 'https://example.com/jobs/dear-motors-fitter',
    },
    {
        company: 'The Warehouse',
        role: 'Casual Team Member (Nightfill)',
        location: 'Te Rapa, Hamilton',
        dateApplied: '2025-10-28',
        status: 'Applied',
        url: 'https://example.com/jobs/warehouse-nightfill',
    },
    {
        company: 'Computer Concepts',
        role: 'Customer Experience Agent (Overnight)',
        location: 'Wellington City, Wellington',
        dateApplied: '2025-10-25',
        status: 'Not selected',
        url: 'https://example.com/jobs/computer-concepts-overnight',
    },
    {
        company: 'Computer Concepts',
        role: 'Service Desk Analyst (Evening shifts)',
        location: 'Wellington City, Wellington',
        dateApplied: '2025-10-25',
        status: 'Not selected',
        url: 'https://example.com/jobs/computer-concepts-evening',
    },
    {
        company: 'Tech Domain',
        role: 'IT Network Engineer',
        location: 'Wellington City, Wellington',
        dateApplied: '2025-10-03',
        status: 'Rejected',
        url: 'https://example.com/jobs/tech-domain-network',
    },
    {
        company: 'Warehouse Stationery',
        role: 'Technology Team Member (Part-Time)',
        location: 'Te Rapa, Hamilton',
        dateApplied: '2025-10-03',
        status: 'Interviewing',
        url: 'https://example.com/jobs/warehouse-stationery-tech',
    },
    {
        company: 'Computer Partners',
        role: 'IT Support Specialist',
        location: 'Masterton 5810',
        dateApplied: '2025-10-20',
        status: 'Not selected',
        url: 'https://example.com/jobs/computer-partners-support',
    },
    {
        company: 'Instant Windscreens & Tinting',
        role: 'Autoglass Fitter Trainee',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-09-19',
        status: 'Offer',
        url: 'https://example.com/jobs/instant-windscreens-trainee',
    },
    {
        company: 'Hill Labs',
        role: 'IT Support Engineer',
        location: 'Hamilton Lake, Waikato',
        dateApplied: '2025-10-26',
        status: 'Expired',
        url: 'https://example.com/jobs/hill-labs-support',
    },
    {
        company: 'Cloud Torque Global Ltd',
        role: 'Support Engineer',
        location: 'Hamilton Central, Waikato',
        dateApplied: '2025-11-01',
        status: 'Unlikely to progress',
        url: 'https://example.com/jobs/cloud-torque-support',
    },
    {
        company: 'Hampshire (NZ) Limited',
        role: 'IT Operations Support Lead',
        location: 'Wellington Central, Wellington',
        dateApplied: '2025-10-25',
        status: 'Expired',
        url: 'https://example.com/jobs/hampshire-it-lead',
    },
    {
        company: 'Aiscorp Limited',
        role: 'Level 1 Helpdesk Technician',
        location: 'Johnsonville, Wellington',
        dateApplied: '2025-11-13',
        status: 'Viewed',
        url: 'https://example.com/jobs/aiscorp-helpdesk',
    },
    {
        company: 'University of Waikato',
        role: 'Student Systems Analyst',
        location: 'Hamilton East, Waikato',
        dateApplied: '2025-10-20',
        status: 'Rejected',
        url: 'https://example.com/jobs/waikato-uni-analyst',
    },
    {
        company: 'Montana Group',
        role: 'Packing & Production Team Member',
        location: 'Te Rapa, Waikato',
        dateApplied: '2025-10-25',
        status: 'Unlikely to progress',
        url: 'https://example.com/jobs/montana-packing',
    },
    {
        company: 'The Instillery',
        role: 'Support Analyst',
        location: 'Hamilton Central, Waikato',
        dateApplied: '2025-10-12',
        status: 'Expired',
        url: 'https://example.com/jobs/instillery-support',
    },
    {
        company: 'Repco New Zealand',
        role: 'Part Time Retail Assistant',
        location: 'Hamilton, Waikato',
        dateApplied: '2025-10-10',
        status: 'Rejected',
        url: 'https://example.com/jobs/repco-retail',
    },
    {
        company: 'PODcom Limited',
        role: 'Helpdesk Support Engineer',
        location: 'Hamilton Central, Waikato',
        dateApplied: '2025-10-05',
        status: 'Unlikely to progress',
        url: 'https://example.com/jobs/podcom-helpdesk',
    },
    {
        company: 'Harvey Norman',
        role: 'Technology Sales Consultant',
        location: 'Hamilton Central, Waikato',
        dateApplied: '2025-10-02',
        status: 'Offer',
        url: 'https://example.com/jobs/harvey-norman-sales',
    },
    {
        company: 'Hamilton Hotel',
        role: 'Front of House',
        location: 'Hamilton Central, Waikato',
        dateApplied: '2025-10-02',
        status: 'Expired',
        url: 'https://example.com/jobs/hamilton-hotel-foh',
    },
];
