import type { JobApplication } from './types';

export const seedApplications: JobApplication[] = [
  {
    id: '1',
    userId: 'user123',
    company: 'Mountain Warehouse',
    role: 'Casual Retail Sales Assistant',
    location: 'Taupo, Waikato',
    dateApplied: '2025-11-17',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'user123',
    company: 'Hamilton City Council',
    role: 'Senior Service Desk Analyst',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-11-17',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'user123',
    company: 'JD Sports Australia & NZ',
    role: 'Footwear Sales Assistant',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-11-17',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'user123',
    company: 'The Just Group (Jay Jays)',
    role: 'Christmas Casual',
    location: 'The Base, Waikato',
    dateApplied: '2025-11-16',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'user123',
    company: 'Bhogal Limited',
    role: 'Courier Driver',
    location: 'Te Rapa, Waikato',
    dateApplied: '2025-11-16',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'user123',
    company: 'Datacom',
    role: 'Application Support Analyst',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-11-14',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '7',
    userId: 'user123',
    company: 'Red Path N Tables',
    role: 'Christmas Helpers',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-11-14',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '8',
    userId: 'user123',
    company: 'DEAR Motors',
    role: 'General Fitter',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-10-30',
    status: 'Viewed',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '9',
    userId: 'user123',
    company: 'The Warehouse',
    role: 'Casual Team Member (Nightfill)',
    location: 'Te Rapa, Hamilton',
    dateApplied: '2025-10-28',
    status: 'Applied',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '10',
    userId: 'user123',
    company: 'Computer Concepts',
    role: 'Customer Experience Agent (Overnight)',
    location: 'Wellington City, Wellington',
    dateApplied: '2025-10-25',
    status: 'Not selected',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '11',
    userId: 'user123',
    company: 'Computer Concepts',
    role: 'Service Desk Analyst (Evening shifts)',
    location: 'Wellington City, Wellington',
    dateApplied: '2025-10-25',
    status: 'Not selected',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '12',
    userId: 'user123',
    company: 'Tech Domain',
    role: 'IT Network Engineer',
    location: 'Wellington City, Wellington',
    dateApplied: '2025-10-03',
    status: 'Not selected',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '13',
    userId: 'user123',
    company: 'Warehouse Stationery',
    role: 'Technology Team Member (Part-Time)',
    location: 'Te Rapa, Hamilton',
    dateApplied: '2025-10-03',
    status: 'Interviewing',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '14',
    userId: 'user123',
    company: 'Computer Partners',
    role: 'IT Support Specialist',
    location: 'Masterton 5810',
    dateApplied: '2025-10-20',
    status: 'Not selected',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '15',
    userId: 'user123',
    company: 'Instant Windscreens & Tinting',
    role: 'Autoglass Fitter Trainee',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-09-19',
    status: 'Interviewing',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '16',
    userId: 'user123',
    company: 'Hill Labs',
    role: 'IT Support Engineer',
    location: 'Hamilton Lake, Waikato',
    dateApplied: '2025-10-26',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '17',
    userId: 'user123',
    company: 'Cloud Torque Global Ltd',
    role: 'Support Engineer',
    location: 'Hamilton Central, Waikato',
    dateApplied: '2025-11-01',
    status: 'Unlikely to progress',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '18',
    userId: 'user123',
    company: 'Hampshire (NZ) Limited',
    role: 'IT Operations Support Lead',
    location: 'Wellington Central, Wellington',
    dateApplied: '2025-10-25',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '19',
    userId: 'user123',
    company: 'Aiscorp Limited',
    role: 'Level 1 Helpdesk Technician',
    location: 'Johnsonville, Wellington',
    dateApplied: '2025-11-13',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '20',
    userId: 'user123',
    company: 'University of Waikato',
    role: 'Student Systems Analyst',
    location: 'Hamilton East, Waikato',
    dateApplied: '2025-10-20',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '21',
    userId: 'user123',
    company: 'Montana Group',
    role: 'Packing & Production Team Member',
    location: 'Te Rapa, Waikato',
    dateApplied: '2025-10-25',
    status: 'Unlikely to progress',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '22',
    userId: 'user123',
    company: 'The Instillery',
    role: 'Support Analyst',
    location: 'Hamilton Central, Waikato',
    dateApplied: '2025-10-12',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '23',
    userId: 'user123',
    company: 'Repco New Zealand',
    role: 'Part Time Retail Assistant',
    location: 'Hamilton, Waikato',
    dateApplied: '2025-10-10',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '24',
    userId: 'user123',
    company: 'PODcom Limited',
    role: 'Helpdesk Support Engineer',
    location: 'Hamilton Central, Waikato',
    dateApplied: '2025-10-05',
    status: 'Unlikely to progress',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '25',
    userId: 'user123',
    company: 'Harvey Norman',
    role: 'Technology Sales Consultant',
    location: 'Hamilton Central, Waikato',
    dateApplied: '2025-10-02',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '26',
    userId: 'user123',
    company: 'Hamilton Hotel',
    role: 'Front of House',
    location: 'Hamilton Central, Waikato',
    dateApplied: '2025-10-02',
    status: 'Expired',
    url: '',
    lastUpdated: new Date().toISOString(),
  },
];
